from tkinter import *
root=Tk()
root.geometry("750x500")
pic=PhotoImage(file="1.png")
f1=Frame(root)
f1.pack()
f2=Frame(root)
f2.pack()
f3=Frame(root)
f3.pack()
l1=Label(f1, text="ajay pandit",font="areal 100 bold", bg="black",fg="white")
l1.pack()
l2=Label(f2,image=pic,font="areal 3 bold",bg="red")
l2.pack()
l3=Label(f3, text="ajay pandit",font="areal 200 bold")
l3.pack()
root.mainloop()
